parcial/Controllers/loginController.cs
using Firebase.Auth;
using Firebase.Storage;
using Microsoft.AspNetCore.Mvc;
using parcial.Models;

namespace parcial.Controllers
{
    public class loginController : Controller
    {
        private readonly DBcontexto _DBcontexto;

        public loginController(DBcontexto DBcontexto)
        {
            _DBcontexto = DBcontexto;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult sesion(String pUsuario, String pass)
        {
            var DataUsuario = (from us in _DBcontexto.usuario
                                    where us.nombre_usuario.Equals(pUsuario) &&  us.password.Equals(pass) && us.empresa == 0 
                               select us).ToList().FirstOrDefault();

            var DataEmpresa = (from us in _DBcontexto.usuario
                               where us.nombre_usuario.Equals(pUsuario) && us.password.Equals(pass) && us.empresa == 1
                               select us).ToList().FirstOrDefault();

            var id = (from us in _DBcontexto.usuario
                        where us.nombre_usuario.Equals(pUsuario) && us.password.Equals(pass) && us.empresa == 0
                        select new 
                        { 
                            us.id_usuario
                        }).ToList().FirstOrDefault();


            if (DataUsuario != null && id != null)
            {
                usuario oUsuario = DataUsuario;

                HttpContext.Session.SetInt32("id_usuario", oUsuario.id_usuario);
                HttpContext.Session.SetString("UsName", oUsuario.nombre_usuario);

                ViewData["usuario"] = DataUsuario;
                return RedirectToAction("index", "usuario");
            }
            else if(DataEmpresa != null)
            {
                usuario oEmpresa = DataEmpresa;

                HttpContext.Session.SetInt32("id_usuario", oEmpresa.id_usuario);
                HttpContext.Session.SetString("UsName", oEmpresa.nombre_usuario);
                ViewData["usuario"] = DataEmpresa;
                return RedirectToAction("index", "empresa");
            }
            else
            {
                TempData["mensaje"] = "Datos incorrectos";
                ViewData["usuario"] = "Datos incorrectos";
                return RedirectToAction("index");
            }

        }
        public IActionResult crear()
        {
            return View();
        }

        //se ingresa de esta manera se debe llamar a otro metedo que haga esa accion y recibir los datos del 
        //formulario
        [HttpPost]
        public async Task<IActionResult> ingresar(usuario pUsuario, IFormFile foto)
        {
            usuario ousuario;
            //agregar la imagen
            //leer el archivo

            if (foto != null) 
            {
                Stream archivoASubir = foto.OpenReadStream();

                String email = "parcial@maill.com";
                String clave = "123456";
                String ruta = "parcial-54edf.appspot.com";
                String api_key = "AIzaSyCFOvWjgguo11serR_6qfI9jRzaOicdsTQ";

                var auth = new FirebaseAuthProvider(new FirebaseConfig(api_key));
                var autenticarFireBase = await auth.SignInWithEmailAndPasswordAsync(email, clave);

                var cancellation = new CancellationTokenSource();
                var tokenUser = autenticarFireBase.FirebaseToken;

                var tareaCargarArchivo = new FirebaseStorage(ruta, new FirebaseStorageOptions
                {
                    AuthTokenAsyncFactory = () => Task.FromResult(tokenUser),
                    ThrowOnCancel = true
                }
                                                            ).Child("fotos")
                                                            .Child(foto.FileName)
                                                            .PutAsync(archivoASubir, cancellation.Token);
                var urlArchivo = await tareaCargarArchivo;

                ViewBag.foto = urlArchivo;
                ousuario = pUsuario;
                ousuario.foto = urlArchivo;
                //agregar la imagen

            }
            else
            {
                ousuario= pUsuario;
            }
            _DBcontexto.usuario.Add(ousuario);
            _DBcontexto.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

parcial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] parcial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/parcial.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    @if (@ViewBag.nombre == null)
    {
        <header>
            <!-- Se usara una condicional para esconder la navbar-->
            <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
                <div class="container">
                    <button class="btn btn-dark" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions"
                            aria-controls="offcanvasWithBothOptions">
                        <i class="fa-solid fa-sliders"></i>
                    </button>
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">Logo</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarScroll">
                        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Empresas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Oferta">Ofertas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="recurso">Recursos</a>
                            </li>
                        </ul>
                        <form class="d-flex" role="search" asp-controller="oferta" asp-action="Buscar">
                            <input class="form-control me-2" type="text" placeholder="Buscar trabajo" aria-label="Search" name="nombre">
                            <button class="btn btn-outline-success" type="submit">Buscar</button>
                        </form>
                        <a class="btn text-light" href="@Url.Action("Index", "login")"><i class="fa-solid fa-user"></i> Ingresar</a>
                    </div>
                </div>
            </nav>
        </header>
    }
    @if (ViewBag.nombre == null)
    {
        <!--Este es el offcanvas (lo recomendado es crear este offcanvas y meterlo en una vista específica de busquedad])-->
        <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions"
         aria-labelledby="offcanvasWithBothOptionsLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Busqueda en base a parametros</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <form asp-controller="oferta" asp-action="BuscarParametro">
                    <h6>Experiencia</h6>
                    <div class="btn-group-vertical" role="group" aria-label="Vertical radio toggle button group">
                        <input type="radio" class="btn-check" name="experiencia" id="vbtn-radioE1" autocomplete="off" value="1" checked>
                        <label class="btn btn-outline-danger" for="vbtn-radioE1">Sin experiencia</label>

                        <input type="radio" class="btn-check" name="experiencia" id="vbtn-radio2E" autocomplete="off" value="2">
                        <label class="btn btn-outline-danger" for="vbtn-radio2E">1 año a más</label>
                    </div>

                    <h6>Salario</h6>
                    <div class="btn-group-vertical" role="group" aria-label="Vertical radio toggle button group">
                        <input type="radio" class="btn-check" name="salario" id="vbtn-radio1" autocomplete="off" value="1" checked>
                        <label class="btn btn-outline-danger" for="vbtn-radio1">$500</label>

                        <input type="radio" class="btn-check" name="salario" id="vbtn-radio2" autocomplete="off" value="2">
                        <label class="btn btn-outline-danger" for="vbtn-radio2">$700</label>

                        <input type="radio" class="btn-check" name="salario" id="vbtn-radio3" autocomplete="off" value="3">
                        <label class="btn btn-outline-danger" for="vbtn-radio3">$1000 y más</label>
                    </div>
                    <br />
                    <button class="btn btn-outline-success mt-3" type="submit">Buscar</button>
                </form>
            </div>
        </div>
    }
  

    <div class="container-fluid p-0">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    @if (@ViewBag.nombre == null)
    {
        <footer>
            <div class="border-top footer text-muted bg-dark pt-2">
                <div class="container">
                    <div class="row text-center d-flex">
                        <div class="col-md-3">
                            <h6 class="text-uppercase font-weight-bold text-light">
                                <i class="fa-solid fa-users"></i> Usuarios: @ViewBag.ConteoUsuarios
                            </h6>
                        </div>

                        <div class="col-md-3">
                            <h6 class="text-uppercase font-weight-bold text-light">
                                <i class="fa-solid fa-suitcase"></i> Empleos publicados: @ViewBag.conteoPublicacion
                            </h6>
                        </div>

                        <div class="col-md-3">
                            <h6 class="text-uppercase font-weight-bold text-light">
                                <i class="fa-solid fa-building-circle-check"></i> Empresas: @ViewBag.ConteoEmpresa
                            </h6>
                        </div>

                        <div class="col-md-3">
                            <h6 class="text-uppercase font-weight-bold text-light">
                                <i class="fa-solid fa-list-check"></i> Solicitudes: @ViewBag.conteoSolicitudes
                            </h6>
                        </div>
                    </div>
                    <h6 class="text-center text-light">©CopyRight Grupo #4</h6>
                </div>
            </div>
        </footer>
   }
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/201886318c.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>